import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/context/AuthContext";
import { ThemeProvider } from "@/lib/context/ThemeContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PreloaderWrapper from "@/components/PreloaderWrapper";
import CartDrawer from "@/components/CartDrawer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-heading" });

export const metadata: Metadata = {
  metadataBase: new URL("https://www.bitiumtechnology.com"),
  title: "Bitium Technology - High-Performance Custom DTF Sheet Builder",
  description: "Create, customize, and order premium DTF prints and apparel online with Bitium Technology.",
  keywords: "DTF prints, apparel, t-shirt design, custom printing, virtual canvas, fabricjs, next.js, Bitium Technology",
  authors: [{ name: "Bitium Technology" }],
  // Note: og:image and twitter:image are auto-generated by Next.js from
  // app/opengraph-image.jpg and app/twitter-image.jpg (file convention).
  // This approach works even when pages use 'use client'.
  openGraph: {
    title: "Bitium Technology - High-Performance Custom DTF Sheet Builder",
    description: "Create, customize, and order premium DTF prints and apparel online with Bitium Technology.",
    url: "https://www.bitiumtechnology.com",
    siteName: "Bitium Technology",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Bitium Technology - High-Performance Custom DTF Sheet Builder",
    description: "Create, customize, and order premium DTF prints and apparel online with Bitium Technology.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased dark ${inter.variable} ${outfit.variable}`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-sans selection:bg-primary/40 selection:text-primary-foreground">
        <ThemeProvider>
          <PreloaderWrapper>
            <AuthProvider>
              <Navbar />
              <main className="flex-grow flex flex-col">{children}</main>
              <Footer />
              <CartDrawer />
            </AuthProvider>
          </PreloaderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
